# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Alice
Welcome, Alice!


In [ ]:
# complete your program here
f = float(input('Please enter the temperature in Fahrenheit: '))

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 140
140.0
140.0F is 60.0 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
# complete your program here
f=float(input('please enter the temperature in Celcius'))
print(f)
f=(c* 9/5) + 32

print(f'{c}C is {f} in Fahrenheit.')

please enter the temperature in Celcius60
60.0
60.0C is 140.0 in Fahrenheit.


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')

if unit.upper() == "C":
    f = (temp * 9/5) + 32
    print(f"{temp:g}C is {f:g} in Fahrenheit")

else:
    c = (temp - 32) * 5/9
    print(f"{temp:g}F is {c:g} in Celsius")



Please enter the temperature: 140
Is this in Celsius or Fahrenheit? f
140F is 60 in Celsius


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
line=("Talk is cheap. Show me the code - Linus Torvalds")
print(len(line))

48


In [ ]:
# Convert the whole string to lower case.
print(line.lower())

talk is cheap. show me the code - linus torvalds


In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(line[9:-9])

heap. Show me the code - Linus


In [ ]:
# Split the sentence into a list of substrings by space ' '.
print(line.split(' '))

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [ ]:
# Given the sentence, output a list of words in lowercase (without symbols such as '.' and '-').
print(line.lower().replace(".", "").replace("-", "").split())

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [ ]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
#vowels = 'aeiou'

count = 0

for v in vowels:
    count += line.lower().count(v)

print(count)


13


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
for i in range(len(line)):
  if line[i].lower() in vowels:print(i)


1
5
10
11
17
21
25
28
30
35
37
41
44


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
    cubes.append(i ** 3)

print(cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Use list comprehension to create the same list
cubes = [i ** 3 for i in range(5)]
print(cubes)


[0, 1, 8, 27, 64]


In [ ]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowels = ['a', 'e', 'i', 'o', 'u']
positions = [i for i in range(len(sentence)) if sentence[i].lower() in vowels]
print(positions)



[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = int(input('How many numbers do you want? '))


# add your code here
a=0
b=1
for i in range(n):
    fibonacci.append(a)
    a, b = b, a + b

print(fibonacci)



How many numbers do you want? 24
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [ ]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {
    'Pfizer': 0.95,
    'Moderna': 0.95,
    'AstraZeneca': 0.72,
    'Johnson & Johnson': 0.66}

print(v_dict)


{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66}


In [ ]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])

Which vaccine? Pfizer
0.95


In [ ]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary

v_dict['Sputnik V'] = 0.914


In [ ]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = 0.5038

In [ ]:
# Print vaccines with efficacy lower than 90%.
for vaccine in v_dict:
    if v_dict[vaccine] < 0.90:
        print(vaccine)


AstraZeneca
Johnson & Johnson
Sinovac


In [ ]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']

In [ ]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here
for ch in sentence:
    if ch != ' ':
        if ch in ch_dict:
            ch_dict[ch] += 1
        else:
            ch_dict[ch] = 1

# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [1]:
import numpy as np

In [3]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([])
np.arange(2, 41, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [4]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([])
np.arange(1, 40, 2)


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [5]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.array([])
np.arange(100).reshape(10, 10)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(loc=0, scale=1, size=(10, 10))
M.shape



(10, 10)

In [10]:
# Count the numbers in M with an absolute value greater than 1.
np.sum(np.abs(M) > 1)


np.int64(31)

In [13]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = int(input('Row count: '))

# Input the number of rows (input another integer >= 3)
c = int(input('column count: '))

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, size=(r, c))
arr

Row count: 10
column count: 20


array([[18, 17, 17, 16, 14, 17, 19, 18, 16, 12, 12, 12, 14, 14, 17, 13,
        18, 12, 14, 12],
       [10, 15, 16, 10, 17, 19, 15, 14, 17, 18, 19, 15, 17, 10, 19, 11,
        17, 19, 15, 15],
       [12, 12, 19, 18, 18, 16, 15, 14, 17, 14, 18, 16, 17, 18, 13, 16,
        10, 13, 16, 17],
       [19, 17, 14, 18, 15, 19, 17, 12, 12, 16, 10, 11, 18, 14, 11, 12,
        18, 18, 12, 17],
       [14, 18, 10, 11, 15, 17, 12, 12, 12, 16, 13, 12, 13, 11, 12, 10,
        17, 14, 19, 17],
       [14, 19, 16, 17, 10, 15, 12, 19, 18, 18, 15, 16, 17, 19, 17, 11,
        16, 11, 11, 19],
       [11, 14, 15, 10, 13, 10, 18, 18, 18, 13, 19, 12, 10, 18, 15, 17,
        11, 13, 17, 11],
       [12, 17, 16, 14, 16, 19, 12, 12, 18, 19, 11, 17, 18, 12, 18, 15,
        11, 15, 15, 17],
       [16, 10, 18, 19, 12, 11, 12, 18, 15, 14, 11, 11, 13, 17, 10, 17,
        16, 10, 15, 13],
       [10, 19, 18, 12, 13, 11, 18, 16, 10, 12, 10, 17, 12, 18, 13, 19,
        15, 13, 16, 18]])

In [15]:
# output the element in the first row and the third column
arr[0, 2]

np.int64(17)

In [24]:
# output the element in the second row and the last column
arr[1,-1]

np.int64(15)

In [22]:
# output the second row of the array
arr[1,]


array([10, 15, 16, 10, 17, 19, 15, 14, 17, 18, 19, 15, 17, 10, 19, 11, 17,
       19, 15, 15])

In [23]:
# output the second last row of the array
arr[-1,]

array([10, 19, 18, 12, 13, 11, 18, 16, 10, 12, 10, 17, 12, 18, 13, 19, 15,
       13, 16, 18])

In [26]:
# output the second column of the array
arr[:,1]

array([17, 15, 12, 17, 18, 19, 14, 17, 10, 19])

In [27]:
# output the second last column of the array
arr[:-1]

array([[18, 17, 17, 16, 14, 17, 19, 18, 16, 12, 12, 12, 14, 14, 17, 13,
        18, 12, 14, 12],
       [10, 15, 16, 10, 17, 19, 15, 14, 17, 18, 19, 15, 17, 10, 19, 11,
        17, 19, 15, 15],
       [12, 12, 19, 18, 18, 16, 15, 14, 17, 14, 18, 16, 17, 18, 13, 16,
        10, 13, 16, 17],
       [19, 17, 14, 18, 15, 19, 17, 12, 12, 16, 10, 11, 18, 14, 11, 12,
        18, 18, 12, 17],
       [14, 18, 10, 11, 15, 17, 12, 12, 12, 16, 13, 12, 13, 11, 12, 10,
        17, 14, 19, 17],
       [14, 19, 16, 17, 10, 15, 12, 19, 18, 18, 15, 16, 17, 19, 17, 11,
        16, 11, 11, 19],
       [11, 14, 15, 10, 13, 10, 18, 18, 18, 13, 19, 12, 10, 18, 15, 17,
        11, 13, 17, 11],
       [12, 17, 16, 14, 16, 19, 12, 12, 18, 19, 11, 17, 18, 12, 18, 15,
        11, 15, 15, 17],
       [16, 10, 18, 19, 12, 11, 12, 18, 15, 14, 11, 11, 13, 17, 10, 17,
        16, 10, 15, 13]])

In [28]:
# output the upper-left 3x3 sub-array
arr[:3, :3]


array([[18, 17, 17],
       [10, 15, 16],
       [12, 12, 19]])

In [31]:
# output the bottom-left 3x3 sub-array
arr[-3:,:3]

array([[12, 17, 16],
       [16, 10, 18],
       [10, 19, 18]])

In [35]:
# output the upper-right 3x3 sub-array
arr[:3 ,-3:]

array([[12, 14, 12],
       [19, 15, 15],
       [13, 16, 17]])

In [36]:
# output the bottom-right 3x3 sub-array
arr[-3:,-3:]

array([[15, 15, 17],
       [10, 15, 13],
       [13, 16, 18]])

In [44]:
# Create a 1-D array from 1 to 50 (inclusive)
A = ...
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A = np.arange(1, 51).reshape(5, 10)


In [46]:
# add a row [51,...,60] to A
A = np.vstack([A, np.arange(51, 61)])

In [48]:
# split the new A (6x10) to two 3x10 arrays A1 and A2

A1, A2 = np.split(A, 2)


In [59]:
# Add 10 to each element of A
A1 = A1 + 10
A2= A2+10



In [65]:
# Calculate the square root of each element in A
print(np.sqrt(A1))
print(np.sqrt(A2))


[[2.14069514 2.16573677 2.1899387  2.21336384 2.23606798 2.25810086
  2.27950706 2.30032663 2.32059579 2.34034732]
 [2.35961106 2.37841423 2.39678173 2.4147364  2.43229928 2.44948974
  2.46632571 2.4828238  2.4989994  2.51486686]
 [2.53043953 2.5457299  2.5607496  2.57550958 2.59002006 2.60429069
  2.6183305  2.63214803 2.64575131 2.65914795]]
[[2.53043953 2.5457299  2.5607496  2.57550958 2.59002006 2.60429069
  2.6183305  2.63214803 2.64575131 2.65914795]
 [2.67234512 2.68534961 2.69816788 2.71080601 2.72326982 2.7355648
  2.74769621 2.75966902 2.771488   2.78315768]
 [2.79468239 2.80606626 2.81731325 2.82842712 2.83941151 2.85026988
  2.86100555 2.87162171 2.88212142 2.89250761]]


In [66]:
# Above, we should have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape
M = np.random.normal(0, 1, (10, 10))

In [67]:
# Print the mean, standard devietion of all numbers in M
print(np.mean(M))
print(np.std(M))


-0.13240899009236964
1.0436890794812004


In [68]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print("Maximum:", np.max(M))
print("3rd quartile:", np.percentile(M, 75))
print("Median:", np.median(M))
print("1st quartile:", np.percentile(M, 25))
print("Minimum:", np.min(M))


Maximum: 1.7832739607907797
3rd quartile: 0.7331444220113787
Median: -0.08471529440832964
1st quartile: -0.808130499097905
Minimum: -2.9772422848794498
